# Generated by Django 2.0.5 on 2018-05-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaperone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('itinerary', models.TextField()),
                ('pupils', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('departing', models.DateTimeField()),
                ('returning', models.DateTimeField()),
                ('funds', models.CharField(max_length=64)),
                ('costs', models.TextField()),
                ('buses', models.IntegerField()),
                ('transported_by', models.CharField(max_length=64)),
                ('transportation_comments', models.TextField()),
                ('standards', models.TextField()),
                ('anticipatory', models.TextField()),
                ('purpose', models.TextField()),
                ('nurse_required', models.NullBooleanField()),
                ('nurse_comments', models.TextField()),
                ('nurse_name', models.CharField(max_length=64)),
                ('directions', models.FileField(upload_to='')),
                ('roster', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='chaperone',
            name='field_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.FieldTrip'),
        ),
    ]
