# Generated by Django 2.0.5 on 2018-05-14 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrip',
            name='email',
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='submitter',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
