# Generated by Django 2.0.5 on 2018-06-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='approval',
            name='building',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='buildings',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='title',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Building'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.IntegerField(choices=[(0, 'Principal'), (1, 'Nurse'), (2, 'Supervisor'), (3, 'Assistant Superintendent'), (4, 'Field Trip Secretary'), (5, 'Secretary of Pupil Personnel Services'), (6, 'Head of Facilites'), (7, 'Secretary of Transportation')]),
        ),
        migrations.AddField(
            model_name='role',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Discipline'),
        ),
    ]
