# Generated by Django 2.0.5 on 2018-05-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='departing',
            field=models.DateTimeField(verbose_name='Date and Time of Departure'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='group',
            field=models.CharField(max_length=64, verbose_name='Class / Group / Club'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='pupils',
            field=models.IntegerField(verbose_name='Number of Pupils'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='returning',
            field=models.DateTimeField(verbose_name='Date and Time Returning to School'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='teachers',
            field=models.IntegerField(verbose_name='Number of Teachers'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='extra_vehicles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Vehicles'),
        ),
    ]
