# Generated by Django 2.0.5 on 2018-05-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('field_trips', '0002_auto_20180507_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Grade'),
        ),
    ]
