# Generated by Django 2.0.5 on 2018-05-14 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0002_auto_20180514_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.Building'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted'),
        ),
    ]
