# Generated by Django 2.0.5 on 2018-06-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0002_auto_20180601_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Building'),
        ),
        migrations.AlterField(
            model_name='role',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Discipline'),
        ),
    ]
