# Generated by Django 2.0.5 on 2018-05-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0003_auto_20180507_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('role', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='anticipatory',
            field=models.TextField(help_text='To be completed with students in advance of trip', verbose_name='Description of Anticipatory Activity'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='costs',
            field=models.TextField(help_text='Please describe all costs in detail. Buses are $75 per hour.'),
        ),
        migrations.RemoveField(
            model_name='fieldtrip',
            name='extra_vehicles',
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='extra_vehicles',
            field=models.ManyToManyField(to='field_trips.Vehicle', verbose_name='Additional Vehicles Required'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='funds',
            field=models.CharField(choices=[('BUILDING', 'Building Budget'), ('STUDENT', 'Student Funded')], max_length=8, verbose_name='Source of Funds'),
        ),
        migrations.RemoveField(
            model_name='fieldtrip',
            name='grades',
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='grades',
            field=models.ManyToManyField(to='field_trips.Grade'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='itinerary',
            field=models.TextField(help_text='Please include time at destination, lunch arrangements, and additional stops.'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='purpose',
            field=models.TextField(help_text='What will the students learn, and HOW?', verbose_name='Description of Educational Value of Trip'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='standards',
            field=models.TextField(help_text='Please be specific.', verbose_name='Unit(s) of Study / Curriculum Standards Addressed During Trip'),
        ),
        migrations.AddField(
            model_name='approval',
            name='field_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.FieldTrip'),
        ),
    ]
