# Generated by Django 2.0.5 on 2018-05-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0003_auto_20180514_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
