# Generated by Django 2.0.5 on 2018-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0004_auto_20180514_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.NullBooleanField()),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.Approver')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.Building')),
            ],
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='directions',
            field=models.FileField(upload_to='field_trips/'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='roster',
            field=models.FileField(upload_to='field_trips/'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.Approver', verbose_name='Approving Supervisor'),
        ),
        migrations.AddField(
            model_name='approval',
            name='field_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.FieldTrip'),
        ),
        migrations.AddField(
            model_name='approval',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_trips.Role'),
        ),
    ]
