# Generated by Django 2.0.5 on 2018-05-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0004_auto_20180507_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
                ('approvers', models.ManyToManyField(to='field_trips.Approver')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='approval',
            name='field_trip',
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='buses',
            field=models.IntegerField(help_text='Each bus seats 52 people.', verbose_name='Number of Buses Required'),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.AddField(
            model_name='approver',
            name='roles',
            field=models.ManyToManyField(to='field_trips.Role'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='building',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Building'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='supervisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Approver'),
        ),
    ]
