# Generated by Django 2.0.5 on 2018-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0004_auto_20180601_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepting_new', models.BooleanField(verbose_name='Accepting New Field Trip Requests')),
                ('window_start', models.DateTimeField(help_text='Only accept field trips with a departure date AFTER this date', verbose_name='Window Start')),
                ('window_end', models.DateTimeField(help_text='Only accept field trips with a departure date BEFORE this date', verbose_name='Window End')),
            ],
        ),
    ]
