# Generated by Django 2.0.5 on 2018-06-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0005_adminoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminoptions',
            name='accepting_new',
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='window_open',
            field=models.BooleanField(default=False, help_text='Are you accepting new field trip requests?', verbose_name='open'),
        ),
        migrations.AlterField(
            model_name='adminoptions',
            name='window_end',
            field=models.DateTimeField(verbose_name='Window End'),
        ),
        migrations.AlterField(
            model_name='adminoptions',
            name='window_start',
            field=models.DateTimeField(verbose_name='Window Start'),
        ),
    ]
