# Generated by Django 2.0.5 on 2018-05-15 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0006_auto_20180515_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='building',
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Approver'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
