# Generated by Django 2.0.5 on 2018-06-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0007_auto_20180607_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminOptions',
            new_name='AdminOption',
        ),
    ]
