# Generated by Django 2.0.5 on 2018-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0007_auto_20180515_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrip',
            name='status',
            field=models.CharField(default='In Progress', max_length=64),
            preserve_default=False,
        ),
    ]
