# Generated by Django 2.0.5 on 2018-05-16 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0008_fieldtrip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
