# Generated by Django 2.0.6 on 2018-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0009_auto_20180618_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrip',
            name='costs',
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='airfare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='baggage',
            field=models.IntegerField(default=0, help_text='Extra Baggage'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='lodging',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='meals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='parking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='registration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='shuttle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='stipend',
            field=models.IntegerField(default=0, help_text='Overnight Stipend'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='tolls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='departing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time of Departure'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='returning',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time Returning to School'),
        ),
    ]
