# Generated by Django 2.0.5 on 2018-05-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0009_auto_20180516_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Approver'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='status',
            field=models.CharField(default='In Progress', max_length=64),
        ),
    ]
