# Generated by Django 2.0.6 on 2018-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0010_auto_20180706_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='airfare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='baggage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra Baggage', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='lodging',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='meals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='parking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='registration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='shuttle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='stipend',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overnight Stipend', max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='ticket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='tolls',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
