# Generated by Django 2.0.5 on 2018-05-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_trips', '0010_auto_20180516_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='field_trips.Building'),
            preserve_default=False,
        ),
    ]
